import { useMemo, useState } from 'react'
import { AlertTriangle, ArrowDownRight, ArrowUpRight, BarChart3, BriefcaseBusiness, CalendarCheck2, CheckCircle2, DollarSign, Filter, Medal, ShieldAlert, Users } from 'lucide-react'
import { Bar, BarChart, CartesianGrid, Cell, ComposedChart, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { ageGroups, attritionDrivers, departmentInsights, executiveSummary, experienceGroups, performanceDistribution, promotionByRole, riskEmployees, salaryByRole, workforceMetrics, workforceTrends } from '../data/workforceInsights'

const sectionConfig = {
  overview: ['Workforce Overview', 'Executive workforce intelligence', 'A current view of workforce health, movement, and the signals that need attention.', BarChart3],
  employees: ['Employee Analytics', 'Workforce composition', 'Demographic, experience, and departmental distribution across 1,470 employees.', Users],
  performance: ['Performance Dashboard', 'Talent performance', 'Performance distribution and its relationship to workforce outcomes.', Medal],
  attendance: ['Attendance Dashboard', 'Workforce availability', 'Attendance trends and department-level availability signals.', CalendarCheck2],
  salary: ['Salary Dashboard', 'Compensation intelligence', 'Monthly income benchmarks by role for compensation planning.', DollarSign],
  promotion: ['Promotion Dashboard', 'Talent development', 'Promotion readiness and probability by role.', ArrowUpRight],
  attrition: ['Attrition Dashboard', 'Retention intelligence', 'Attrition trends, drivers, and intervention priorities.', ArrowDownRight],
  risk: ['Workforce Risk Center', 'AI risk monitoring', 'Prioritized employee-level risk signals and recommended actions.', ShieldAlert],
}
const colors = ['#1d4ed8', '#0891b2', '#f59e0b', '#e11d48', '#7c3aed']
const tooltipStyle = { border: '1px solid #e2e8f0', borderRadius: 8, fontSize: 12, boxShadow: '0 4px 12px rgba(15, 23, 42, 0.08)' }

function WorkforceInsightsPage({ section = 'overview', filters }) {
  const [title, eyebrow, description, Icon] = sectionConfig[section] || sectionConfig.overview
  const [localDepartment, setLocalDepartment] = useState('All')
  const department = filters?.department && filters.department !== 'All' ? filters.department : localDepartment
  const departments = department === 'All' ? departmentInsights : departmentInsights.filter((item) => item.name === department)
  const metrics = useMemo(() => {
    if (department === 'All') return workforceMetrics
    const item = departmentInsights.find((entry) => entry.name === department)
    return { ...workforceMetrics, totalEmployees: item.employees, activeEmployees: Math.round(item.employees * 0.8), attritionRate: item.attrition, healthScore: item.health, attendance: item.attendance, overtimeHours: item.overtime }
  }, [department])
  return <main className="mx-auto max-w-[1680px] p-4 sm:p-6 lg:p-8"><header className="mb-6 flex flex-wrap items-start justify-between gap-4"><div><p className="flex items-center gap-2 text-[11px] font-bold uppercase tracking-[0.16em] text-blue-700"><Icon size={14} /> {eyebrow}</p><h1 className="mt-2 text-2xl font-bold tracking-tight text-slate-950 sm:text-3xl">{title}</h1><p className="mt-2 max-w-2xl text-sm text-slate-500">{description}</p></div><label className="flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs font-semibold text-slate-600 shadow-sm"><Filter size={14} className="text-blue-600" /><span className="sr-only">Department</span><select value={department} onChange={(event) => setLocalDepartment(event.target.value)} className="bg-transparent outline-none"><option>All</option>{departmentInsights.map((item) => <option key={item.name}>{item.name}</option>)}</select></label></header>{section === 'overview' && <Overview metrics={metrics} departments={departments} />}{section === 'employees' && <Employees departments={departments} />}{section === 'performance' && <Performance />}{section === 'attendance' && <Attendance departments={departments} />}{section === 'salary' && <Salary />}{section === 'promotion' && <Promotion />}{section === 'attrition' && <Attrition />}{section === 'risk' && <RiskCenter department={department} />}</main>
}

function KpiGrid({ items }) { return <section className="grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-4">{items.map(({ label, value, tone = 'slate' }) => <article key={label} className="rounded-lg border border-slate-200 bg-white p-4 shadow-sm"><p className="text-[11px] font-semibold uppercase tracking-wide text-slate-500">{label}</p><p className={`mt-2 text-2xl font-bold ${tone === 'red' ? 'text-rose-600' : tone === 'green' ? 'text-emerald-600' : tone === 'amber' ? 'text-amber-600' : 'text-slate-900'}`}>{value}</p></article>)}</section> }
function Panel({ title, children, className = '' }) { return <article className={`min-w-0 rounded-lg border border-slate-200 bg-white p-4 shadow-sm sm:p-5 ${className}`}><h2 className="mb-3 text-sm font-bold text-slate-800">{title}</h2>{children}</article> }
function ChartFrame({ children, height = 270 }) { return <div style={{ height }} className="w-full">{children}</div> }
function Overview({ metrics, departments }) { return <><KpiGrid items={[['Total Employees', metrics.totalEmployees.toLocaleString()], ['Active Employees', metrics.activeEmployees.toLocaleString(), 'green'], ['Attrition Rate', `${metrics.attritionRate}%`, 'red'], ['Workforce Health', `${metrics.healthScore}/100`, 'green']].map(([label, value, tone]) => ({ label, value, tone }))} /><div className="mt-5 grid gap-4 xl:grid-cols-[1.2fr_0.8fr]"><Panel title="Executive workforce summary"><div className="grid gap-3 sm:grid-cols-2">{executiveSummary.map((item) => <div key={item} className="flex gap-2 rounded-lg bg-slate-50 p-3 text-xs leading-5 text-slate-600"><CheckCircle2 size={15} className="mt-0.5 shrink-0 text-emerald-500" />{item}</div>)}</div></Panel><Panel title="Department health"><div className="space-y-4">{departments.map((item) => <div key={item.name}><div className="flex justify-between text-xs font-semibold text-slate-600"><span>{item.shortName}</span><span>{item.health}%</span></div><div className="mt-1.5 h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-blue-600" style={{ width: `${item.health}%` }} /></div></div>)}</div></Panel></div><div className="mt-4 grid gap-4 xl:grid-cols-2"><Panel title="Employee trend"><ChartFrame><ResponsiveContainer><LineChart data={workforceTrends}><CartesianGrid vertical={false} stroke="#e2e8f0" strokeDasharray="3 3" /><XAxis dataKey="month" tick={{ fontSize: 11 }} /><YAxis tick={{ fontSize: 11 }} /><Tooltip contentStyle={tooltipStyle} /><Line type="monotone" dataKey="employees" stroke="#1d4ed8" strokeWidth={3} dot={false} /></LineChart></ResponsiveContainer></ChartFrame></Panel><Panel title="Department distribution"><ChartFrame><ResponsiveContainer><BarChart data={departments} margin={{ left: -18 }}><CartesianGrid vertical={false} stroke="#e2e8f0" strokeDasharray="3 3" /><XAxis dataKey="shortName" tick={{ fontSize: 11 }} /><YAxis tick={{ fontSize: 11 }} /><Tooltip contentStyle={tooltipStyle} /><Bar dataKey="employees" fill="#0891b2" radius={[4, 4, 0, 0]} /></BarChart></ResponsiveContainer></ChartFrame></Panel></div></> }
function Employees({ departments }) { return <><KpiGrid items={[{ label: 'Employees', value: departments.reduce((sum, item) => sum + item.employees, 0).toLocaleString() }, { label: 'Average Tenure', value: `${workforceMetrics.avgTenure} yrs` }, { label: 'Male / Female', value: '58% / 42%' }, { label: 'Active Workforce', value: workforceMetrics.activeEmployees.toLocaleString(), tone: 'green' }]} /><div className="mt-5 grid gap-4 xl:grid-cols-3"><Panel title="Employees by department" className="xl:col-span-2"><ChartFrame><ResponsiveContainer><BarChart data={departments}><CartesianGrid vertical={false} stroke="#e2e8f0" strokeDasharray="3 3" /><XAxis dataKey="shortName" /><YAxis /><Tooltip contentStyle={tooltipStyle} /><Bar dataKey="employees" fill="#1d4ed8" radius={[4, 4, 0, 0]} /></BarChart></ResponsiveContainer></ChartFrame></Panel><Panel title="Age group distribution"><ChartFrame><ResponsiveContainer><PieChart><Pie data={ageGroups} dataKey="value" nameKey="name" innerRadius="55%" outerRadius="78%" stroke="none">{ageGroups.map((item, index) => <Cell key={item.name} fill={colors[index]} />)}</Pie><Tooltip contentStyle={tooltipStyle} /></PieChart></ResponsiveContainer></ChartFrame></Panel></div><div className="mt-4 grid gap-4 xl:grid-cols-2"><Panel title="Experience distribution"><ChartFrame height={230}><ResponsiveContainer><BarChart data={experienceGroups}><CartesianGrid vertical={false} stroke="#e2e8f0" /><XAxis dataKey="name" tick={{ fontSize: 10 }} /><YAxis tickFormatter={(value) => `${value}%`} /><Tooltip contentStyle={tooltipStyle} /><Bar dataKey="value" fill="#0891b2" radius={[4, 4, 0, 0]} /></BarChart></ResponsiveContainer></ChartFrame></Panel><Panel title="Department attrition comparison"><ChartFrame height={230}><ResponsiveContainer><BarChart data={departments}><CartesianGrid vertical={false} stroke="#e2e8f0" /><XAxis dataKey="shortName" /><YAxis tickFormatter={(value) => `${value}%`} /><Tooltip contentStyle={tooltipStyle} /><Bar dataKey="attrition" fill="#e11d48" radius={[4, 4, 0, 0]} /></BarChart></ResponsiveContainer></ChartFrame></Panel></div></> }
function Performance() { return <><KpiGrid items={[{ label: 'Average Rating', value: `${workforceMetrics.avgPerformance} / 5` }, { label: 'Top Performers', value: workforceMetrics.topPerformers.toLocaleString(), tone: 'green' }, { label: 'Low Performers', value: workforceMetrics.lowPerformers.toLocaleString(), tone: 'red' }, { label: 'Average KPI Score', value: `${workforceMetrics.avgKpiScore}%`, tone: 'green' }]} /><div className="mt-5 grid gap-4 xl:grid-cols-2"><Panel title="Performance rating distribution"><ChartFrame><ResponsiveContainer><BarChart data={performanceDistribution}><CartesianGrid vertical={false} stroke="#e2e8f0" /><XAxis dataKey="name" tick={{ fontSize: 10 }} /><YAxis /><Tooltip contentStyle={tooltipStyle} /><Bar dataKey="value" fill="#7c3aed" radius={[4, 4, 0, 0]} /></BarChart></ResponsiveContainer></ChartFrame></Panel><Panel title="Performance and attrition correlation"><ChartFrame><ResponsiveContainer><ComposedChart data={performanceDistribution}><CartesianGrid vertical={false} stroke="#e2e8f0" /><XAxis dataKey="name" tick={{ fontSize: 10 }} /><YAxis yAxisId="left" /><YAxis yAxisId="right" orientation="right" tickFormatter={(value) => `${value}%`} /><Tooltip contentStyle={tooltipStyle} /><Bar yAxisId="left" dataKey="value" fill="#c4b5fd" radius={[4, 4, 0, 0]} /><Line yAxisId="right" dataKey="attrition" stroke="#e11d48" strokeWidth={3} /></ComposedChart></ResponsiveContainer></ChartFrame></Panel></div></> }
function Attendance({ departments }) { return <><KpiGrid items={[{ label: 'Overall Attendance', value: `${workforceMetrics.attendance}%`, tone: 'green' }, { label: 'Average Leave Days', value: `${workforceMetrics.avgLeaveDays} days` }, { label: 'Overtime Hours', value: `${workforceMetrics.overtimeHours} hrs`, tone: 'amber' }, { label: 'Best Department', value: 'HR', tone: 'green' }]} /><div className="mt-5 grid gap-4 xl:grid-cols-2"><Panel title="Monthly attendance trend"><ChartFrame><ResponsiveContainer><LineChart data={workforceTrends}><CartesianGrid vertical={false} stroke="#e2e8f0" /><XAxis dataKey="month" /><YAxis domain={[85, 100]} tickFormatter={(value) => `${value}%`} /><Tooltip contentStyle={tooltipStyle} /><Line dataKey="attendance" stroke="#059669" strokeWidth={3} dot={false} /></LineChart></ResponsiveContainer></ChartFrame></Panel><Panel title="Attendance by department"><ChartFrame><ResponsiveContainer><BarChart data={departments}><CartesianGrid vertical={false} stroke="#e2e8f0" /><XAxis dataKey="shortName" /><YAxis domain={[85, 100]} tickFormatter={(value) => `${value}%`} /><Tooltip contentStyle={tooltipStyle} /><Bar dataKey="attendance" fill="#059669" radius={[4, 4, 0, 0]} /></BarChart></ResponsiveContainer></ChartFrame></Panel></div></> }
function Salary() { return <><KpiGrid items={[{ label: 'Director Income', value: '$18.5K' }, { label: 'Manager Income', value: '$15.2K' }, { label: 'Specialist Income', value: '$9.8K' }, { label: 'Executive Income', value: '$6.2K' }]} /><div className="mt-5 grid gap-4 xl:grid-cols-2"><Panel title="Monthly income by job role"><ChartFrame><ResponsiveContainer><BarChart data={salaryByRole} layout="vertical" margin={{ left: 20 }}><CartesianGrid horizontal={false} stroke="#e2e8f0" /><XAxis type="number" tickFormatter={(value) => `$${value / 1000}K`} /><YAxis type="category" dataKey="name" /><Tooltip contentStyle={tooltipStyle} formatter={(value) => [`$${value.toLocaleString()}`, 'Monthly income']} /><Bar dataKey="value" fill="#0f766e" radius={[0, 4, 4, 0]} /></BarChart></ResponsiveContainer></ChartFrame></Panel><Panel title="Compensation planning note"><div className="flex h-full min-h-[220px] items-center rounded-lg bg-slate-50 p-5 text-sm leading-6 text-slate-600"><BriefcaseBusiness size={22} className="mr-3 shrink-0 text-teal-600" />Use role-level income benchmarks alongside performance and promotion readiness when reviewing compensation equity.</div></Panel></div></> }
function Promotion() { return <><KpiGrid items={[{ label: 'Eligible for Promotion', value: workforceMetrics.eligiblePromotion.toLocaleString(), tone: 'green' }, { label: 'Promotion Probability', value: `${workforceMetrics.promotionProbability}%`, tone: 'green' }, { label: 'Promotion Rate', value: `${workforceMetrics.promotionRate}%` }, { label: 'Review Cycle', value: 'Q3 2024' }]} /><div className="mt-5 grid gap-4 xl:grid-cols-2"><Panel title="Promotion probability by job role"><ChartFrame><ResponsiveContainer><BarChart data={promotionByRole}><CartesianGrid vertical={false} stroke="#e2e8f0" /><XAxis dataKey="name" /><YAxis domain={[0, 100]} tickFormatter={(value) => `${value}%`} /><Tooltip contentStyle={tooltipStyle} /><Bar dataKey="value" fill="#f59e0b" radius={[4, 4, 0, 0]} /></BarChart></ResponsiveContainer></ChartFrame></Panel><Panel title="Promotion readiness signal"><div className="space-y-4 pt-3"><Signal label="Performance and KPI trend" value="Strong" tone="green" /><Signal label="Tenure readiness" value="Watch" tone="amber" /><Signal label="Eligible population" value="127 employees" tone="blue" /></div></Panel></div></> }
function Signal({ label, value, tone }) { const classes = { green: 'bg-emerald-50 text-emerald-700', amber: 'bg-amber-50 text-amber-700', blue: 'bg-blue-50 text-blue-700' }; return <div className="flex items-center justify-between gap-3 rounded-lg border border-slate-100 p-3 text-xs"><span className="text-slate-600">{label}</span><span className={`rounded-full px-2.5 py-1 font-bold ${classes[tone]}`}>{value}</span></div> }
function Attrition() { return <><KpiGrid items={[{ label: 'Overall Attrition', value: `${workforceMetrics.attritionRate}%`, tone: 'red' }, { label: 'High-Risk Employees', value: workforceMetrics.highRiskEmployees.toLocaleString(), tone: 'red' }, { label: 'Highest-Risk Department', value: 'Sales', tone: 'amber' }, { label: 'Trend vs. Prior Year', value: '-1.3%', tone: 'green' }]} /><div className="mt-5 grid gap-4 xl:grid-cols-2"><Panel title="Monthly attrition trend"><ChartFrame><ResponsiveContainer><LineChart data={workforceTrends}><CartesianGrid vertical={false} stroke="#e2e8f0" /><XAxis dataKey="month" /><YAxis domain={[16, 22]} tickFormatter={(value) => `${value}%`} /><Tooltip contentStyle={tooltipStyle} /><Line dataKey="attrition" stroke="#e11d48" strokeWidth={3} dot={false} /></LineChart></ResponsiveContainer></ChartFrame></Panel><Panel title="Key attrition drivers"><ChartFrame><ResponsiveContainer><BarChart data={attritionDrivers} layout="vertical" margin={{ left: 22 }}><CartesianGrid horizontal={false} stroke="#e2e8f0" /><XAxis type="number" tickFormatter={(value) => `${value}%`} /><YAxis type="category" dataKey="name" tick={{ fontSize: 10 }} /><Tooltip contentStyle={tooltipStyle} /><Bar dataKey="value" fill="#e11d48" radius={[0, 4, 4, 0]} /></BarChart></ResponsiveContainer></ChartFrame></Panel></div></> }
function RiskCenter({ department }) { const [level, setLevel] = useState('All'); const rows = riskEmployees.filter((item) => (department === 'All' || item.department === department) && (level === 'All' || item.level === level)); return <><KpiGrid items={[{ label: 'Composite Risk Score', value: '58', tone: 'amber' }, { label: 'High Risk', value: '4', tone: 'red' }, { label: 'Medium Risk', value: '4', tone: 'amber' }, { label: 'Monitoring Status', value: 'Live', tone: 'green' }]} /><Panel title="High attrition risk panel" className="mt-5"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2 text-xs text-slate-500"><AlertTriangle size={15} className="text-amber-500" /> Prioritized by composite risk score</div><select value={level} onChange={(event) => setLevel(event.target.value)} className="rounded-md border border-slate-200 bg-white px-3 py-2 text-xs text-slate-600 outline-none"><option>All</option><option>High</option><option>Medium</option></select></div><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-xs"><thead className="border-b border-slate-200 uppercase tracking-wide text-slate-400"><tr>{['Employee', 'Department', 'Score', 'Level', 'Main risk factor', 'Tenure', 'Performance', 'Recommended action'].map((heading) => <th key={heading} className="px-3 py-3 font-bold">{heading}</th>)}</tr></thead><tbody>{rows.map((item) => <tr key={item.name} className="border-b border-slate-100 text-slate-600 hover:bg-slate-50"><td className="px-3 py-3 font-semibold text-slate-800">{item.name}</td><td className="px-3 py-3">{item.department}</td><td className="px-3 py-3 font-bold text-slate-900">{item.score}</td><td className="px-3 py-3"><span className={`rounded-full px-2 py-1 font-bold ${item.level === 'High' ? 'bg-rose-50 text-rose-700' : 'bg-amber-50 text-amber-700'}`}>{item.level}</span></td><td className="px-3 py-3">{item.factor}</td><td className="px-3 py-3">{item.tenure}</td><td className="px-3 py-3">{item.performance} / 5</td><td className="px-3 py-3">{item.action}</td></tr>)}</tbody></table></div>{!rows.length && <p className="py-8 text-center text-xs text-slate-400">No employees match the selected filters.</p>}</Panel></> }

export default WorkforceInsightsPage