# -*- coding: utf-8 -*-
"""Infosys project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JiyRNlFk0aiUFDJ9N5Dd5d5n4EM9HMPg
"""

import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings("ignore")

df = pd.read_csv("hr.csv")

df.head()

df.shape

df.info()

df.isnull().sum()

df.duplicated().sum()

df.reset_index(drop=True, inplace=True)

df.info()

df.to_csv("HR_Analytics_Cleaned.csv",index=False)

df.shape

"""--------------------------------------------------------------------------------"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use("ggplot")
# %matplotlib inline

df = pd.read_csv("HR_Analytics_Cleaned.csv")

total_employees = len(df)

print("Total Employees :", total_employees)

average_age = round(df["Age"].mean(),2)

print("Average Age :", average_age)

average_income = round(df["MonthlyIncome"].mean(),2)

print("Average Monthly Income :", average_income)

average_experience = round(df["TotalWorkingYears"].mean(),2)

print("Average Working Years :", average_experience)

kpi = pd.DataFrame({
    "Metric":[
        "Total Employees",
        "Average Age",
        "Average Monthly Income",
        "Average Working Years",

    ],
    "Average Value":[
        total_employees,
        average_age,
        average_income,
        average_experience,

    ]
})

kpi

plt.figure(figsize=(6,5))

sns.countplot(data=df,
              x="Attrition")

plt.title("Employee Attrition Distribution")
plt.xlabel("Attrition")
plt.ylabel("Employee Count")

plt.show()

attrition_percentage = (
    df["Attrition"]
      .value_counts(normalize=True)
      *100
)

print(attrition_percentage)

plt.figure(figsize=(8,5))

sns.countplot(
    data=df,
    x="Department",
    hue="Attrition"
)

plt.title("Department-wise Employee Attrition")
plt.xlabel("Department")
plt.ylabel("Employee Count")
plt.legend(title="Attrition")

plt.show()

department_attrition_percent = pd.crosstab(
    df["Department"],
    df["Attrition"],
    normalize="index"
) * 100

department_attrition_percent.round(2)

"""--------------------------------------------------------------------------------"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    ConfusionMatrixDisplay
)

df = pd.read_csv("HR_Analytics_Cleaned.csv")

df_ml = df.copy()

le = LabelEncoder()

for col in df_ml.select_dtypes(include="object").columns:
    df_ml[col] = le.fit_transform(df_ml[col])

X = df_ml.drop("Attrition", axis=1)
y = df_ml["Attrition"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

"""### **LogisticRegression👇**"""

lr_model = LogisticRegression(random_state=42)

lr_model.fit(X_train, y_train)

y_pred_lr = lr_model.predict(X_test)

y_prob_lr = lr_model.predict_proba(X_test)[:, 1]

accuracy_lr = accuracy_score(y_test, y_pred_lr)
precision_lr = precision_score(y_test, y_pred_lr)
recall_lr = recall_score(y_test, y_pred_lr)
f1_lr = f1_score(y_test, y_pred_lr)
roc_auc_lr = roc_auc_score(y_test, y_prob_lr)

print("Accuracy :", accuracy_lr)
print("Precision:", precision_lr)
print("Recall   :", recall_lr)
print("F1 Score :", f1_lr)
print("ROC-AUC  :", roc_auc_lr)

cm = confusion_matrix(y_test, y_pred_lr)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=lr_model.classes_
)

disp.plot(cmap="Blues")
plt.title("Logistic Regression - Confusion Matrix")
plt.show()

"""### **Decision Tree👇**"""

dt_model = DecisionTreeClassifier(random_state=42)

dt_model.fit(X_train, y_train)

y_pred_dt = dt_model.predict(X_test)

y_prob_dt = dt_model.predict_proba(X_test)[:, 1]

accuracy_dt = accuracy_score(y_test, y_pred_dt)
precision_dt = precision_score(y_test, y_pred_dt)
recall_dt = recall_score(y_test, y_pred_dt)
f1_dt = f1_score(y_test, y_pred_dt)
roc_auc_dt = roc_auc_score(y_test, y_prob_dt)

print("Accuracy :", accuracy_dt)
print("Precision:", precision_dt)
print("Recall   :", recall_dt)
print("F1 Score :", f1_dt)
print("ROC-AUC  :", roc_auc_dt)

cm = confusion_matrix(y_test, y_pred_dt)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=dt_model.classes_
)

disp.plot(cmap="Blues")

plt.title("Decision Tree - Confusion Matrix")

plt.show()

"""### **Random Forest👇**"""

rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf_model.fit(X_train, y_train)

y_pred_rf = rf_model.predict(X_test)

y_prob_rf = rf_model.predict_proba(X_test)[:, 1]

accuracy_rf = accuracy_score(y_test, y_pred_rf)
precision_rf = precision_score(y_test, y_pred_rf)
recall_rf = recall_score(y_test, y_pred_rf)
f1_rf = f1_score(y_test, y_pred_rf)
roc_auc_rf = roc_auc_score(y_test, y_prob_rf)

print("Accuracy :", accuracy_rf)
print("Precision:", precision_rf)
print("Recall   :", recall_rf)
print("F1 Score :", f1_rf)
print("ROC-AUC  :", roc_auc_rf)

cm = confusion_matrix(y_test, y_pred_rf)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=rf_model.classes_
)

disp.plot(cmap="Blues")

plt.title("Random Forest - Confusion Matrix")

plt.show()

"""### **XGBoost👇**"""

xgb_model = XGBClassifier(
    random_state=42,
    eval_metric="logloss"
)

xgb_model.fit(X_train, y_train)

y_pred_xgb = xgb_model.predict(X_test)

y_prob_xgb = xgb_model.predict_proba(X_test)[:, 1]

accuracy_xgb = accuracy_score(y_test, y_pred_xgb)
precision_xgb = precision_score(y_test, y_pred_xgb)
recall_xgb = recall_score(y_test, y_pred_xgb)
f1_xgb = f1_score(y_test, y_pred_xgb)
roc_auc_xgb = roc_auc_score(y_test, y_prob_xgb)

print("Accuracy :", accuracy_xgb)
print("Precision:", precision_xgb)
print("Recall   :", recall_xgb)
print("F1 Score :", f1_xgb)
print("ROC-AUC  :", roc_auc_xgb)

cm = confusion_matrix(y_test, y_pred_xgb)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=xgb_model.classes_
)

disp.plot(cmap="Blues")

plt.title("XGBoost - Confusion Matrix")

plt.show()

#Comparison
comparison = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Decision Tree",
        "Random Forest",
        "XGBoost"
    ],
    "Accuracy": [
        accuracy_lr,
        accuracy_dt,
        accuracy_rf,
        accuracy_xgb
    ],
    "Precision": [
        precision_lr,
        precision_dt,
        precision_rf,
        precision_xgb
    ],
    "Recall": [
        recall_lr,
        recall_dt,
        recall_rf,
        recall_xgb
    ],
    "F1 Score": [
        f1_lr,
        f1_dt,
        f1_rf,
        f1_xgb
    ],
    "ROC-AUC": [
        roc_auc_lr,
        roc_auc_dt,
        roc_auc_rf,
        roc_auc_xgb
    ]
})

comparison = comparison.round(4)

comparison

"""------------------------------------------------------------------------

### **Data Dictionary👇**
"""

import pandas as pd

# Load cleaned dataset
df = pd.read_csv("HR_Analytics_Cleaned.csv")

# Create Data Dictionary
data_dictionary = pd.DataFrame({
    "Column Name": df.columns,
    "Data Type": df.dtypes.astype(str),
    "Missing Values": df.isnull().sum().values,
    "Unique Values": df.nunique().values
})

data_dictionary

"""### **Data Validation Report👇**"""

validation_report = pd.DataFrame({

    "Validation Check":[
        "Total Rows",
        "Total Columns",
        "Missing Values",
        "Duplicate Records",
        "Constant Columns",
        "Numeric Columns",
        "Categorical Columns"
    ],

    "Result":[
        df.shape[0],
        df.shape[1],
        df.isnull().sum().sum(),
        df.duplicated().sum(),
        len(df.columns[df.nunique()==1]),
        len(df.select_dtypes(include=["int64","float64"]).columns),
        len(df.select_dtypes(include=["object"]).columns)
    ]

})

validation_report

"""## **Analytics Requirements (Dataset Summary)👇**"""

analytics_requirements = pd.DataFrame({

    "Requirement":[

        "Total Employees",
        "Average Age",
        "Average Monthly Income",
        "Average Years At Company",
        "Attrition Rate (%)"

    ],

    "Value":[

        len(df),

        round(df["Age"].mean(),2),

        round(df["MonthlyIncome"].mean(),2),

        round(df["YearsAtCompany"].mean(),2),

        round((df["Attrition"].value_counts(normalize=True)["Yes"])*100,2)

    ]

})

analytics_requirements